FROM node:23-alpine AS builder

WORKDIR /app

COPY Frontend/package*.json ./
COPY Frontend/tsconfig.json ./

RUN npm install

COPY Frontend/ ./

RUN npm run build

# Etapa de producción con serve
FROM node:23-alpine

WORKDIR /app

# Instala 'serve'
RUN npm install -g serve

# Copia el resultado del build
COPY --from=builder /app/dist ./dist

EXPOSE 3000

CMD ["serve", "-s", "dist", "-l", "3000"]
