# Etapa 1: Build del frontend
FROM node:23-alpine AS build

WORKDIR /app

COPY Frontend/package*.json ./
COPY Frontend/tsconfig.json ./

RUN npm install

COPY Frontend/ ./

RUN npm run build

# Etapa 2: Servir con nginx
FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
