FROM node:23-alpine AS builder

WORKDIR /app

# Copia y construye el proyecto
COPY Frontend/package*.json ./
COPY Frontend/tsconfig.json ./
COPY Frontend/vite.config.* ./
COPY Frontend/src ./src
COPY Frontend/public ./public

RUN npm install
RUN npm run build

# Etapa de producción con serve
FROM node:23-alpine

WORKDIR /app

# Instala 'serve'
RUN npm install -g serve

# Copia el resultado del build
COPY --from=builder /app/dist ./dist

EXPOSE 3000

CMD ["serve", "-s", "dist", "-l", "3000"]
