version: '3.8'

services:
  backend:
    build: ./Backend
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "8080:8080"

  frontend:
    build: ./Frontend
    depends_on:
      - backend
    ports:
      - "80:80"
