# Construcción (build) usando Maven
FROM eclipse-temurin:21-jdk-alpine AS builder

WORKDIR /app

COPY Backend/ ./Backend/

WORKDIR /app/Backend

RUN chmod +x ./mvnw

ENV MAVEN_OPTS="-Xmx256m"

RUN ./mvnw package -DskipTests

# Imagen runtime solo con JRE y JAR empaquetado
FROM eclipse-temurin:21-jre-alpine

WORKDIR /app

COPY --from=builder /app/Backend/target/*.jar app.jar

EXPOSE 8080

CMD ["java", "-jar", "app.jar"]
